name: myenv
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - streamlit==1.48.1
      - fastai==2.7.14
      - torch==2.2.2
      - torchvision==0.17.2
      - plotly==6.3.0
      - fasttransform
