name: myenv
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.29.0
      - fastai==2.7.14
      - torch==2.0.1
      - torchvision==0.15.2
      - plotly==5.22.0
      - fasttransform
